services:
  dashy:
    image: 'lissy93/dashy:latest'
    restart: unless-stopped
    container_name: dashy
    volumes:
      - './conf.yml:/app/user-data/conf.yml'
    # ports:
    # - '8080:8080'
    labels:
      - traefik.enable=true
      - traefik.http.routers.dash.rule=Host(`dash.localhost`)
      - traefik.http.routers.dash.entrypoints=http
      - traefik.http.services.dash.loadbalancer.server.port=8080

networks:
  default:
    name: main
    external: true
